//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezYonetimS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BagliOlacagiIs
    {
        public Nullable<int> mevcutIsId { get; set; }
        public Nullable<int> BagliOlacagiIsId { get; set; }
        public int Id { get; set; }
    
        public virtual YapilacakIs YapilacakIs { get; set; }
        public virtual YapilacakIs YapilacakIs1 { get; set; }
    }
}
