//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezYonetimS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneriTez
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OneriTez()
        {
            this.Bildirim = new HashSet<Bildirim>();
            this.Toplanti = new HashSet<Toplanti>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Ozet { get; set; }
        public System.DateTime TeklifTarihi { get; set; }
        public int OgrenciId { get; set; }
        public int DanismanId { get; set; }
        public int DilId { get; set; }
        public int TezTuruId { get; set; }
        public int BasvuruDurumuId { get; set; }
        public string AnahtarKelimeler { get; set; }
    
        public virtual BasvuruDurumu BasvuruDurumu { get; set; }
        public virtual BasvuruDurumu BasvuruDurumu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bildirim> Bildirim { get; set; }
        public virtual Dil Dil { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        public virtual Kullanici Kullanici2 { get; set; }
        public virtual Kullanici Kullanici3 { get; set; }
        public virtual TezTuru TezTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toplanti> Toplanti { get; set; }
    }
}
