//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezYonetimS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TezBasvuru
    {
        public int Id { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public int OgrenciId { get; set; }
        public int TezId { get; set; }
        public int BasvuruDurumuId { get; set; }
    
        public virtual BasvuruDurumu BasvuruDurumu { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Tez Tez { get; set; }
    }
}
