//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezYonetimS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toplanti_YapilacakIs
    {
        public int Id { get; set; }
        public Nullable<int> YapiacakIsId { get; set; }
        public Nullable<int> ToplantiId { get; set; }
    
        public virtual Toplanti Toplanti { get; set; }
        public virtual YapilacakIs YapilacakIs { get; set; }
    }
}
