//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezYonetimS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toplanti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Toplanti()
        {
            this.Not = new HashSet<Not>();
            this.Toplanti_YapilacakIs = new HashSet<Toplanti_YapilacakIs>();
        }
    
        public int Id { get; set; }
        public string Adı { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.TimeSpan Saat { get; set; }
        public Nullable<int> Ogrenci1 { get; set; }
        public Nullable<int> Ogrenci2 { get; set; }
        public Nullable<int> Danisman { get; set; }
        public Nullable<int> DurumId { get; set; }
        public Nullable<int> TezId { get; set; }
        public Nullable<int> OneriId { get; set; }
        public Nullable<int> TeklifId { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        public virtual Kullanici Kullanici2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Not> Not { get; set; }
        public virtual OneriTez OneriTez { get; set; }
        public virtual Tez Tez { get; set; }
        public virtual ToplantiDurumu ToplantiDurumu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toplanti_YapilacakIs> Toplanti_YapilacakIs { get; set; }
    }
}
