//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezYonetimS
{
    using System;
    using System.Collections.Generic;
    
    public partial class YapilacakIs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YapilacakIs()
        {
            this.AltIs = new HashSet<AltIs>();
            this.BagliIs = new HashSet<BagliIs>();
            this.BagliIs1 = new HashSet<BagliIs>();
            this.BagliOlacagiIs = new HashSet<BagliOlacagiIs>();
            this.BagliOlacagiIs1 = new HashSet<BagliOlacagiIs>();
            this.Bildirim = new HashSet<Bildirim>();
            this.Not = new HashSet<Not>();
            this.Toplanti_YapilacakIs = new HashSet<Toplanti_YapilacakIs>();
            this.YapilacakIs_Sohbet = new HashSet<YapilacakIs_Sohbet>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Ogrenci1Id { get; set; }
        public Nullable<int> Ogrenci2Id { get; set; }
        public Nullable<int> DanismanId { get; set; }
        public Nullable<int> IsDurumuId { get; set; }
        public Nullable<int> IsOncelikId { get; set; }
        public Nullable<int> TezId { get; set; }
        public Nullable<System.DateTime> planlananBaslamaT { get; set; }
        public Nullable<System.DateTime> planlananBitisT { get; set; }
        public Nullable<System.DateTime> gercekBaslamaT { get; set; }
        public Nullable<System.DateTime> gercekBitisT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AltIs> AltIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BagliIs> BagliIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BagliIs> BagliIs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BagliOlacagiIs> BagliOlacagiIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BagliOlacagiIs> BagliOlacagiIs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bildirim> Bildirim { get; set; }
        public virtual IsDurumu IsDurumu { get; set; }
        public virtual IsOncellik IsOncellik { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        public virtual Kullanici Kullanici2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Not> Not { get; set; }
        public virtual Tez Tez { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toplanti_YapilacakIs> Toplanti_YapilacakIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YapilacakIs_Sohbet> YapilacakIs_Sohbet { get; set; }
    }
}
