//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezYonetimS
{
    using System;
    using System.Collections.Generic;
    
    public partial class YapilacakIs_Sohbet
    {
        public Nullable<int> YapilacakIsId { get; set; }
        public Nullable<int> SohbetId { get; set; }
        public int Id { get; set; }
    
        public virtual Sohbet Sohbet { get; set; }
        public virtual YapilacakIs YapilacakIs { get; set; }
    }
}
